apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.labels }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.labels }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}
          name: {{ .Values.labels }}
          imagePullPolicy: Always
          resources: 
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
