apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace.name }}
  annotations: 
    field.cattle.io/projectName: "{{ .Values.annotation.project }}"
    opflex.cisco.com/endpoint-group: '{"tenant":"{{ .Values.annotation.tenant }}","app-profile":"{{ .Values.annotation.appprofile }}","name":"{{ .Values.annotation.name }}"}'
