apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    kubernetes.io/metadata.name: {{ .Values.namespace.name }}
  annotations: 
    field.cattle.io/projectId: "{{ .Values.annotation.project }}"
    opflex.cisco.com/endpoint-group: '{"tenant":"{{ .Values.annotation.tenant }}","app-profile":"{{ .Values.annotation.appprofile }}","name":"{{ .Values.annotation.name }}"}'
    field.cattle.io/resourceQuota: >-
      {"limit":{"limitsCpu":"100m","limitsMemory":"120Mi","requestsCpu":"90m","requestsMemory":"108Mi"}}

