apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJiY3ItZGUwMS5pbnNpZGUuYm9zY2guY2xvdWQiOnsidXNlcm5hbWUiOiJwb29yZmUiLCJwYXNzd29yZCI6IjgzZmI0YzhlLTA2YTYtNGRmNC1iN2ZiLWVlYjY3YjViMzlmMiIsImF1dGgiOiJjRzl2Y21abE9qZ3pabUkwWXpobExUQTJZVFl0TkdSbU5DMWlOMlppTFdWbFlqWTNZalZpTXpsbU1nPT0ifX19
kind: Secret
metadata:
  name: msrcred
  namespace: {{ .Values.namespace.name }}
