apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.labels }}
  namespace: {{ .Values.namespace.name }}
spec:
  rules:
  - host: {{ .Values.namespace.name }}.{{ .Values.annotation.wildcard }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.labels }}
          servicePort: 80
