apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.labels }}
  name: {{ .Values.labels }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.labels }}
  type: ClusterIP
